sudo: required
services:
  - docker

script:
  - docker build . -t tbsw
  - docker run --rm -it -v $PWD/workspace:/root/workspace-test/workspace tbsw testbeam-luise.py
  - ls workspace/ && stat workspace
  - docker ps -a
