sudo: required
services:
  - docker

script:
  - docker pull kuchosauronad0/tbsw
  - docker run --rm -it -v $PWD/workspace:/root/workspace-test/workspace kuchosauronad0/tbsw testbeam-luise.py
  - ls workspace/ && stat workspace
  - docker ps -a
